name: BDD Automation CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repo
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Cache Maven dependencies (speeds up builds)
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Install dependencies and run tests
    - name: Run BDD Tests
      run: mvn clean test -Denv=dev -Dcucumber.filter.tags="@test" -B

    # Step 5 (Optional): Publish reports
    - name: Upload Cucumber Reports
      uses: actions/upload-artifact@v4
      with:
        name: cucumber-reports
        path: target/cucumber-reports
