name: BDD Automation CI - Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-bdd-tests:
    runs-on: windows-latest

    steps:
    # 1️⃣ Checkout repository
    - name: Checkout Repository
      uses: actions/checkout@latest

    # 2️⃣ Set up JDK
    - name: Set up JDK 17
      uses: actions/setup-java@latest
      with:
        distribution: temurin
        java-version: 17

    # 3️⃣ Cache Maven dependencies
    - name: Cache Maven packages
      uses: actions/cache@latest
      with:
        path: C:\Users\runneradmin\.m2\repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # 4️⃣ Run BDD tests with your parameters
    - name: Run BDD Tests
      run: mvn clean test -B -DbrowserMode=headle -Dcucumber.filter.tags="@test6" -DthreadCount=10 -Denv=dev -Dbrowser=chrome

    # 5️⃣ Print test results (optional)
    - name: Print Cucumber results
      run: dir target\cucumber-reports
