name: BDD Automation CI - Linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-bdd-tests:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout repository
    - name: Checkout Repository
      uses: actions/checkout@latest

    # 2️⃣ Set up JDK
    - name: Set up JDK 17
      uses: actions/setup-java@latest
      with:
        distribution: temurin
        java-version: 17

    # 3️⃣ Cache Maven dependencies
    - name: Cache Maven packages
      uses: actions/cache@latest
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # 4️⃣ Install Chrome (for Selenium)
    - name: Install Google Chrome
      run: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt update
        sudo apt install -y google-chrome-stable

    # 5️⃣ Run BDD tests with Maven parameters
    - name: Run BDD Tests
      run: mvn clean test -B -DbrowserMode=headle -Dcucumber.filter.tags="@test6" -DthreadCount=10 -Denv=dev -Dbrowser=chrome

    # 6️⃣ Generate Cucumber HTML report
    - name: Generate Cucumber HTML report
      run: |
        echo "Generating HTML report..."
        if [ -f target/cucumber-reports/cucumber.json ]; then
          mvn io.cucumber:cucumber-reporting-maven-plugin:report
        else
          echo "No cucumber.json found, skipping HTML report generation."
        fi

    # 7️⃣ Show report folder
    - name: Show report folder
      run: ls -R target/cucumber-reports
